name: serial_port
version: 0.3.0-dev
description: Dart extension library to communicate on serial port.
author: Nicolas Francois  <nicolas.franc@gmail.com>
homepage: https://github.com/nfrancois/serial_port
environnment:
  sdk: '>=1.9.1 <2.0.0'
dev_dependencies:
  #grinder: ">=0.7.0 <0.8.0"
  grinder:
    git: https://github.com/google/grinder.dart.git
  ccompile: ">=0.2.9 <0.3.0"
  test: ">=0.12.0 <0.13.0"
  dart_coveralls: ">=0.1.11 <0.2.0"
